// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import { Test } from "forge-std/Test.sol";
import { UnderwritingVerifier } from "../src/UnderwritingVerifier.sol";
import { ITeeMachineRegistry } from "../src/interfaces/ITeeMachineRegistry.sol";

/// @notice Stand-in for FCC's MachineManager facet.
/// @dev Faithfully reproduces the behaviour that matters: unregistered machines REVERT with
/// TeeNotFound() rather than returning zero. Confirmed against Coston2 (selector 0xceb05b68).
contract MockMachineRegistry is ITeeMachineRegistry {
    error TeeNotFound();

    mapping(address => uint256) internal _extensionId;
    mapping(address => uint8) internal _status;
    mapping(address => bool) internal _known;

    function setMachine(address teeId, uint256 extensionId, uint8 status) external {
        _extensionId[teeId] = extensionId;
        _status[teeId] = status;
        _known[teeId] = true;
    }

    function getExtensionId(address teeId) external view returns (uint256) {
        if (!_known[teeId]) revert TeeNotFound();
        return _extensionId[teeId];
    }

    function getTeeMachineStatus(address teeId) external view returns (uint8) {
        if (!_known[teeId]) revert TeeNotFound();
        return _status[teeId];
    }

    function getRandomTeeIds(uint256, uint256) external pure returns (address[] memory) {
        return new address[](0);
    }

    function getActiveTeeMachines(uint256) external pure returns (address[] memory, string[] memory) {
        return (new address[](0), new string[](0));
    }
}

/// @notice The load-bearing test suite: proves UnderwritingVerifier reconstructs byte-for-byte the
/// digest that tee-node actually signs.
///
/// Fixtures in test/fixtures/tee-signatures.json are generated by backend/tools-fixturegen, which
/// links against the REAL tee-node v0.0.24 and go-flare-common v1.2.2 packages and calls their
/// ActionResult.Hash(), signing.Payload.Hash() and utils.Sign(). So these tests compare our Solidity
/// against Flare's own Go implementation, not against our reading of it. If Flare changes the scheme,
/// regenerating the fixtures turns a silent Coston2 failure into a loud local one.
contract UnderwritingVerifierTest is Test {
    uint256 internal constant EXTENSION_ID = 66_000;
    uint256 internal constant COSTON2_CHAIN_ID = 114;

    UnderwritingVerifier internal verifier;
    MockMachineRegistry internal registry;

    struct Fixture {
        uint256 chainId;
        bytes data;
        bytes32 digest;
        bytes32 id;
        bytes32 innerHash;
        uint256 issuedAt;
        uint256 maxLtvBips;
        uint256 riskTier;
        bytes signature;
        uint256 status;
        address expectedTeeId;
        address borrower;
        bytes32 xrplAddressHash;
        uint256 expiry;
    }

    function setUp() public {
        // Fixtures are signed for chain 114; block.chainid feeds the digest, so the fork must match.
        vm.chainId(COSTON2_CHAIN_ID);
        registry = new MockMachineRegistry();
        verifier = new UnderwritingVerifier(ITeeMachineRegistry(address(registry)), EXTENSION_ID);
    }

    function _loadFixture(string memory name) internal view returns (Fixture memory f) {
        string memory json = vm.readFile("test/fixtures/tee-signatures.json");
        string memory base = string.concat("$[?(@.name == '", name, "')]");
        f.chainId = vm.parseJsonUint(json, string.concat(base, ".chainId"));
        f.data = vm.parseJsonBytes(json, string.concat(base, ".data"));
        f.digest = vm.parseJsonBytes32(json, string.concat(base, ".digest"));
        f.id = vm.parseJsonBytes32(json, string.concat(base, ".id"));
        f.innerHash = vm.parseJsonBytes32(json, string.concat(base, ".innerHash"));
        f.signature = vm.parseJsonBytes(json, string.concat(base, ".signature"));
        f.status = vm.parseJsonUint(json, string.concat(base, ".status"));
        f.expectedTeeId = vm.parseJsonAddress(json, string.concat(base, ".expectedTeeId"));
        f.borrower = vm.parseJsonAddress(json, string.concat(base, ".borrower"));
        f.xrplAddressHash = vm.parseJsonBytes32(json, string.concat(base, ".xrplAddressHash"));
        f.riskTier = vm.parseJsonUint(json, string.concat(base, ".riskTier"));
        f.maxLtvBips = vm.parseJsonUint(json, string.concat(base, ".maxLtvBips"));
        f.issuedAt = vm.parseJsonUint(json, string.concat(base, ".issuedAt"));
        f.expiry = vm.parseJsonUint(json, string.concat(base, ".expiry"));
    }

    /// @dev The single most important assertion in the repo: our packed inner hash equals Go's.
    function test_actionResultHash_matchesGoImplementation() public view {
        Fixture memory f = _loadFixture("tier3_coston2");
        bytes32 got = verifier.actionResultHash(
            f.data, f.id, verifier.SUBMISSION_TAG_THRESHOLD_HASH(), uint8(f.status)
        );
        assertEq(got, f.innerHash, "innerHash must match tee-node ActionResult.Hash()");
    }

    /// @dev Proves the outer abi.encode payload matches go-flare-common signing.Payload.Hash().
    function test_signingDigest_matchesGoImplementation() public view {
        Fixture memory f = _loadFixture("tier3_coston2");
        assertEq(verifier.signingDigest(f.innerHash), f.digest, "digest must match signing.Payload.Hash()");
    }

    /// @dev Proves the EIP-191 wrapper is applied. Without toEthSignedMessageHash this recovers a
    /// wrong address *silently* — the exact bug this fixture exists to catch.
    function test_recoverTeeId_matchesGoSigner() public view {
        Fixture memory f = _loadFixture("tier3_coston2");
        address got = verifier.recoverTeeId(f.data, f.id, uint8(f.status), f.signature);
        assertEq(got, f.expectedTeeId, "must recover the Go signer address");
    }

    function test_verifyAttestation_happyPath() public {
        Fixture memory f = _loadFixture("tier3_coston2");
        registry.setMachine(f.expectedTeeId, EXTENSION_ID, verifier.TEE_STATUS_PRODUCTION());

        (UnderwritingVerifier.CreditAttestation memory att, address teeId) =
            verifier.verifyAttestation(f.data, f.id, uint8(f.status), f.signature);

        assertEq(teeId, f.expectedTeeId, "teeId");
        assertEq(att.borrower, f.borrower, "borrower");
        assertEq(att.xrplAddressHash, f.xrplAddressHash, "xrplAddressHash");
        assertEq(att.riskTier, uint8(f.riskTier), "riskTier");
        assertEq(att.maxLTVBips, uint16(f.maxLtvBips), "maxLTVBips");
        assertEq(att.issuedAt, uint64(f.issuedAt), "issuedAt");
        assertEq(att.expiry, uint64(f.expiry), "expiry");
    }

    /// @dev A tier-0 attestation must verify just as well — "no credit" is a valid signed outcome,
    /// not an error. Regression guard against treating tier 0 as falsy.
    function test_verifyAttestation_tierZeroIsValid() public {
        Fixture memory f = _loadFixture("tier0_coston2");
        registry.setMachine(f.expectedTeeId, EXTENSION_ID, verifier.TEE_STATUS_PRODUCTION());

        (UnderwritingVerifier.CreditAttestation memory att,) =
            verifier.verifyAttestation(f.data, f.id, uint8(f.status), f.signature);
        assertEq(att.riskTier, 0, "tier 0 must verify");
    }

    // --- negative cases -----------------------------------------------------

    /// @dev A signature from a key that is not a registered TEE machine. This is the primary forgery
    /// path, and it must fail closed.
    function test_verifyAttestation_revertsForUnregisteredSigner() public {
        Fixture memory f = _loadFixture("tier3_coston2");
        // deliberately do not register the machine
        vm.expectRevert(
            abi.encodeWithSelector(UnderwritingVerifier.UnknownTeeMachine.selector, f.expectedTeeId)
        );
        verifier.verifyAttestation(f.data, f.id, uint8(f.status), f.signature);
    }

    /// @dev A real TEE machine, but registered to somebody else's extension.
    function test_verifyAttestation_revertsForWrongExtension() public {
        Fixture memory f = _loadFixture("tier3_coston2");
        registry.setMachine(f.expectedTeeId, EXTENSION_ID + 1, verifier.TEE_STATUS_PRODUCTION());
        vm.expectRevert(
            abi.encodeWithSelector(
                UnderwritingVerifier.WrongExtension.selector, f.expectedTeeId, EXTENSION_ID + 1
            )
        );
        verifier.verifyAttestation(f.data, f.id, uint8(f.status), f.signature);
    }

    /// @dev Our machine, but banned/paused rather than PRODUCTION.
    function test_verifyAttestation_revertsForNonProductionMachine() public {
        Fixture memory f = _loadFixture("tier3_coston2");
        registry.setMachine(f.expectedTeeId, EXTENSION_ID, 3);
        vm.expectRevert(
            abi.encodeWithSelector(
                UnderwritingVerifier.TeeMachineNotInProduction.selector, f.expectedTeeId, uint8(3)
            )
        );
        verifier.verifyAttestation(f.data, f.id, uint8(f.status), f.signature);
    }

    /// @dev Pending (>=2) and error (0) results must never be accepted as credit.
    function test_verifyAttestation_revertsForNonSuccessStatus() public {
        Fixture memory f = _loadFixture("tier3_coston2");
        registry.setMachine(f.expectedTeeId, EXTENSION_ID, verifier.TEE_STATUS_PRODUCTION());
        vm.expectRevert(abi.encodeWithSelector(UnderwritingVerifier.InvalidStatus.selector, uint8(0)));
        verifier.verifyAttestation(f.data, f.id, 0, f.signature);
    }

    /// @dev Tampering with the payload changes innerHash, so recovery yields a different address,
    /// which is then unregistered. Proves the payload is genuinely covered by the signature.
    function test_verifyAttestation_revertsWhenDataTampered() public {
        Fixture memory f = _loadFixture("tier3_coston2");
        registry.setMachine(f.expectedTeeId, EXTENSION_ID, verifier.TEE_STATUS_PRODUCTION());

        bytes memory tampered = f.data;
        tampered[63] = bytes1(uint8(tampered[63]) ^ 0x01); // flip a bit in riskTier's word

        address recovered = verifier.recoverTeeId(tampered, f.id, uint8(f.status), f.signature);
        assertTrue(recovered != f.expectedTeeId, "tampered payload must not recover the real signer");
    }

    /// @dev Replaying a valid signature under a different instruction id must not verify.
    function test_verifyAttestation_revertsWhenInstructionIdSwapped() public view {
        Fixture memory f = _loadFixture("tier3_coston2");
        address recovered =
            verifier.recoverTeeId(f.data, bytes32(uint256(f.id) + 1), uint8(f.status), f.signature);
        assertTrue(recovered != f.expectedTeeId, "id is covered by the signature");
    }

    /// @dev chainId is inside the digest, so a Coston2 signature must not verify on another chain.
    /// This is the cross-chain replay guard, and it comes free from Flare's scheme.
    function test_recoverTeeId_differsOnAnotherChain() public {
        Fixture memory f = _loadFixture("tier3_coston2");
        vm.chainId(1);
        address recovered = verifier.recoverTeeId(f.data, f.id, uint8(f.status), f.signature);
        assertTrue(recovered != f.expectedTeeId, "signature must not replay across chains");
    }

    /// @dev Fuzz: no random signature should ever recover a registered machine.
    function testFuzz_randomSignatureNeverVerifies(bytes32 r, bytes32 s, uint8 vRaw) public {
        Fixture memory f = _loadFixture("tier3_coston2");
        registry.setMachine(f.expectedTeeId, EXTENSION_ID, verifier.TEE_STATUS_PRODUCTION());

        uint8 v = 27 + (vRaw % 2);
        bytes memory sig = abi.encodePacked(r, s, v);

        try verifier.verifyAttestation(f.data, f.id, uint8(f.status), sig) returns (
            UnderwritingVerifier.CreditAttestation memory, address teeId
        ) {
            assertTrue(teeId != f.expectedTeeId, "random signature must not impersonate the TEE");
        } catch {
            // reverting is the expected outcome
        }
    }
}
